# Generated by Django 6.1.1 on 2026-09-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='description',
        ),
        migrations.AddField(
            model_name='letter',
            name='spoken_name',
            field=models.CharField(default='ahna', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='letter',
            name='category',
            field=models.CharField(choices=[('uyir', 'Uyir'), ('mey', 'Mey'), ('uyir_mey', 'Uyir-Mey'), ('aytham', 'Aytham')], max_length=20),
        ),
        migrations.AlterField(
            model_name='letter',
            name='display_order',
            field=models.PositiveIntegerField(),
        ),
    ]
