# Generated by Django 6.1.1 on 2026-09-08 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_lesson_lessonletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonletter',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_letters', to='learning.lesson'),
        ),
        migrations.AlterField(
            model_name='lessonletter',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_letters', to='learning.letter'),
        ),
    ]
