# Generated by Django 6.1.1 on 2026-09-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_quizattempt_questionattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='options',
            field=models.JSONField(default=list),
        ),
    ]
