# Generated by Django 6.1.1 on 2026-09-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_questionattempt_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionattempt',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='question_type',
            field=models.CharField(choices=[('sound', 'Sound')], max_length=50),
        ),
    ]
